#dev_trw_lb_homepage:
#    pattern:  /hello/{name}
#    defaults: { _controller: DevTrwLbBundle:Default:index }

dev_trw_lb_homepage:
    pattern:  /
    defaults: { _controller: DevTrwLbBundle:Dashboard:index }
